/*
 * This is just a log file containing Auditors that are inserted into the LIVE Database. It is the development
 * lead's responsibilty to have this file properly synched with the entries present in LIVE Db. 
 */

--DU 4 Auditors
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0879', 'mamallan.krishnan', 1, 'DEP036', 'DU4', 'mamallan.krishnan@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0281',	'ramachandra.ambati', 1, 'DEP036', 'DU4', 'ramachandra.ambati@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0315',	'suganya.arjunan', 1, 'DEP036', 'DU4', 'suganya.arjunan@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0420',	'packiaraj.dharmaraja', 1, 'DEP036', 'DU4', 'packiaraj.dharmaraja@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0795',	'kesavan.manickam', 1, 'DEP036', 'DU4', 'kesavan.manickam@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0615',	'krishna.seetharaman', 1, 'DEP036', 'DU4', 'krishna.seetharaman@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0134',	'sudhakar.kamalakar', 1, 'DEP036', 'DU4', 'sudhakar.kamalakar@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0805',	'jeevanand.rajendran', 1, 'DEP036', 'DU4', 'jeevanand.rajendran@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE1092',	'ganesan.jeevanandam', 1, 'DEP036', 'DU4', 'ganesan.jeevanandam@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0525',	'anbuselvam.prakasam', 1, 'DEP036', 'DU4', 'anbuselvam.prakasam@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0267',	'aravind.swaminathan', 1, 'DEP036', 'DU4', 'aravind.swaminathan@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0792',	'rajesh.kalaivanan', 1, 'DEP036', 'DU4', 'rajesh.kalaivanan@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0644',	'thangavel.sundaram', 1, 'DEP036', 'DU4', 'thangavel.sundaram@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0980', 'mamallan.krishnan', 1, 'DEP036', 'DU4', 'mamallan.krishnan@aspiresys.com', 'ACE0791', CURRENT_DATE(), 'ACE0791', CURRENT_DATE() );


--DU 1 Auditors
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0157', 'hanmandlu.taidalwar', 1, 'DEP023', 'DU1', 'hanmandlu.taidalwar@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0147', 'gayathri.nagarajan', 1, 'DEP023', 'DU1', 'gayathri.nagarajan@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0457', 'balakrishnan.arumugam', 1, 'DEP023', 'DU1', 'balakrishnan.arumugam@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0156', 'gopenath.palanisamy', 1, 'DEP023', 'DU1', 'gopenath.palanisamy@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0900', 'sasikumar.sundaram', 1, 'DEP023', 'DU1', 'sasikumar.sundaram@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0917', 'harikrishna.anandhan', 1, 'DEP023', 'DU1', 'harikrishna.anandhan@aspiresys.com', 'ACE0791', CURRENT_DATE(), 'ACE0791', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE1014', 'karthikeyan.govindar', 1, 'DEP023', 'DU1', 'karthikeyan.govindarasu@aspiresys.com', 'ACE0791', CURRENT_DATE(), 'ACE0791', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0279', 'mohammad.bhaji', 1, 'DEP023', 'DU1', 'mohammad.bhaji@aspiresys.com', 'ACE0791', CURRENT_DATE(), 'ACE0791', CURRENT_DATE() );


--ATG Auditors
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0106', 'muthu.velappan', 1, 'DEP017', 'ATG', 'muthu.velappan@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0011', 'jothi.rengarajan', 1, 'DEP017', 'ATG', 'jothi.rengarajan@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0301', 'murugan.govindasamy', 1, 'DEP017', 'ATG', 'murugan.govindasamy@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0496', 'prakash.nagaswamy', 1, 'DEP017', 'ATG', 'prakash.nagaswamy@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );

--DU 2 Auditors
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0034', 'hariharan.nagarajan', 1, 'DEP024', 'DU2', 'hariharan.nagarajan@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0228', 'sajeev.sreekantan', 1, 'DEP024', 'DU2', 'sajeev.sreekantan@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0067', 'bala.krishnamurthy', 1, 'DEP024', 'DU2', 'bala.krishnamurthy@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0053', 'prabakar.marimuthu', 1, 'DEP024', 'DU2', 'prabakar.marimuthu@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0170', 'nithianandam.karounakarane', 1, 'DEP024', 'DU2', 'nithianandam.karounakarane@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0832', 'srini.nallagounder', 1, 'DEP024', 'DU2', 'srini.nallagounder@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0517', 'gokul.muralidharan', 1, 'DEP024', 'DU2', 'gokul.muralidharan@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0614', 'karthik.ravinthar', 1, 'DEP024', 'DU2', 'karthik.ravinthar@aspiresys.com', 'ACE0106', CURRENT_DATE(), 'ACE0106', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0980', 'yogendran.gopalakrishnan', 1, 'DEP024', 'DU2', 'yogendran.gopalakrishnan@aspiresys.com', 'ACE0791', CURRENT_DATE(), 'ACE0791', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0476', 'ratnavel.sundramurthi', 1, 'DEP024', 'DU2', 'ratnavel.sundramurthi@aspiresys.com', 'ACE0791', CURRENT_DATE(), 'ACE0791', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE0614', 'karthik.ravinthar', 1, 'DEP024', 'DU2', 'karthik.ravinthar@aspiresys.com', 'ACE0791', CURRENT_DATE(), 'ACE0791', CURRENT_DATE() );
INSERT INTO auditor ( ace_no, name, active, dept_id, dept_name, email, created_by, created_on, last_modified_by, last_modified_on ) VALUES ( 'ACE1193', 'chandramouli.parasur', 1, 'DEP024', 'DU2', 'chandramouli.parasuraman@aspiresys.com', 'ACE0791', CURRENT_DATE(), 'ACE0791', CURRENT_DATE() );



